spring.application.name=mycoolapp

coach.name=John Doe
team.name=The A-Team

# management.endpoints.web.exposure.include=health,info,metrics
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My Cool App
info.app.description=This is a cool application built with Spring Boot.
info.app.version=1.0.0