version: '3'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: udemycourse
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306